  import type { Metadata } from "next";
  import { Geist, Geist_Mono } from "next/font/google";
  import "./globals.css";
  import Header from "@/components/header";
  import { ClerkProvider } from "@clerk/nextjs";
  import { ThemeProvider } from "next-themes";
import { Toaster } from "@/components/ui/sonner";

  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} bg-gray-900`}
        >
          <Toaster/>
          <ClerkProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <div className="px-4 pt-2">
                <Header />
              </div>
              <div className="min-h-screen w-full ">
                {children}
              </div>
            </ThemeProvider>
          </ClerkProvider>
        </body>
      </html>
    );
  }
